### PR TITLE
refactor: clean-up lyrics code

### PR DESCRIPTION
**Pull request by SunsetTechuila**

### CODE REVIEW

**Comment by Astromations** [comment]
Haven't been keeping up with Spotify updates. Has my lyricsPadding function become redundant? It's needed to keep the lyrics cinema view and sidebars from overlapping.

**Comment by SunsetTechuila** [comment]
> Has my lyricsPadding function become redundant?

not at all, I replaced it with https://github.com/Astromations/Hazy/blob/d47e1b991e7eab08d4f4052fba7e2ffada210307/hazy.js#L196-L199

**Comment by Astromations** [comment]
Doesn't seem to fix what it was meant to 

image

**Comment by SunsetTechuila** [comment]
How to reproduce?

**Comment by Astromations** [comment]
Oh yeah my bad. Open the lyrics cinema view and expand album cover from the Now Playing Bar

**Comment by SunsetTechuila** [comment]
now the right sidebar remains hidden like in stock spotify

**Comment by Astromations** [comment]
If I wanted to keep it hidden I'd just have disabled collapse button functionality when lyrics are in cinema view. I'd like it to be possible to keep the sidebar and cinema lyrics open, though it does cause some problems with the expansion of the left sidebar I have to workout.

**Comment by SunsetTechuila** [comment]
here you go

**Comment by Astromations** [comment]
Looks like it works. Thank you!

**Pull request merged**
