### PR TITLE
fix: transparent window controls in global nav

### PR DESCRIPTION
**Pull request by sanoojes**
Fix transparent window controls with global nav

Current:
image

Fixed:
image

### CODE REVIEW

**Comment by sanoojes** [comment]
@Astromations should i make the global nav buttons like this
image

Changed css
```css
.main-globalNav-icon {
    aspect-ratio: 1 / 1;
    background-color: var(--spice-main);
    border-radius: var(--button-border);
}

.spotify__container--is-desktop.spotify__os--is-windows .Root__globalNav {
    padding-inline: 58px 135px;
}
```

**Comment by Astromations** [comment]
No. It'll look out of place since it isn't framed in a container. The transparent background looks fine. Though you could try and match the css style of the search bar to that of the non-global nav layout. Thanks for all the help btw. Exams have been eating up a lot of my time so I appreciate it.

**Comment by sanoojes** [comment]
> No. It'll look out of place since it isn't framed in a container. The transparent background looks fine. Though you could try and match the css style of the search bar to that of the non-global nav layout. Thanks for all the help btw. Exams have been eating up a lot of my time so I appreciate it.

oo good i will help out as i can in my free time

**Comment by sanoojes** [comment]
image
should i make the search bar like this in global nav layout?

**Pull request merged**
