### PR TITLE
Fixed border-radius on album image container

### PR DESCRIPTION
**Pull request by Jack-LP**
Removes the white background behind the album cover by rounding the container corners

### CODE REVIEW

**Comment by Astromations** [comment]
Can't say I'm experiencing nor have received any complaints about this issue. 

image

Could you please send a screenshot of what things look like on your end. Also, the border radius should be 8px to match the already established rounding of the image itself.

**Comment by Jack-LP** [comment]
Spotify_yQGHN7Q3ok

Here's what it looks like on my end, I tried an 8px border-radius and it still left a small white outline around the corners, the image inside still retains its border-radius of 8px and doesn't visually change.

**Comment by Astromations** [comment]
I see. What's your operating system and Spotify/Spicetify version.

**Comment by Astromations** [comment]
Received another complaint about this recently. It looks like for some systems ```main-entityHeader-imageContainer``` has a white background and for others it's transparent. I also see what you mean about the 8px border radius not fixing the issue. Gonna push your fix right away. Thanks.

**Comment by Astromations** [comment]
Reopening

**Pull request closed without merging**
