### PR TITLE
fix: transparent window controls

### PR DESCRIPTION
**Pull request by sanoojes**
it fixes the transperent window controls diamensions.
still it has a bug in control nav it works perfect with global nav

issue preview:
<video src="https://github.com/Astromations/Hazy/assets/93819264/903437bd-8b52-448e-b49c-a54cda32448d"></video>
fixed preview:
<video src="https://github.com/Astromations/Hazy/assets/93819264/c58a5c54-2cb5-4763-b1a4-e176ef1a9046"></video>

### CODE REVIEW

**Review by Zuntie — CHANGES_REQUESTED** [review]
Your solution doesn't work universally. On macOS and Linux, it would look like this:
image
Instead of:
image

While it improves the design on Windows, it worsens the design on macOS and Linux.

In my opinion, the design would look worse on those operating systems compared to the existing problem.
_I haven't tested this on Linux or macOS, as I didn't have the time. I only read your code._

**Comment by Astromations** [comment]
I think it's better MacOS and Linux return to default than have the buggy layout. This is a fine tentative fix.

**Comment by sanoojes** [comment]
> Your solution doesn't work universally. On macOS and Linux, it would look like this: image Instead of: image
> 
> While it improves the design on Windows, it worsens the design on macOS and Linux.
> 
> In my opinion, the design would look worse on those operating systems compared to the existing problem. _I haven't tested this on Linux or macOS, as I didn't have the time. I only read your code._

it will only work no windows and does not cause a issue with other os i think the existing problem was much worse than the new one new one has some bugs on scaling in ( a border appearing under the controls  other than that i think its a solid fix)

**Comment by Zuntie** [comment]
> it will only work no windows and does not cause a issue with other os i think the existing problem was much worse than the new one new one has some bugs on scaling in ( a border appearing under the controls other than that i think its a solid fix)

Of course, that's my bad. I know some Linux distros would have this problem, but it should be good for now.
As said in my message, it would only look worse on those specific unsupported distros. On others, it would look great.

MacOS doesn't have this problem at all, because they use their own specific controllers.

Great commits by the way!

**Comment by sanoojes** [comment]
i will check on that do you know which all distros are affected by it ?

**Comment by Zuntie** [comment]
> i will check on that do you know which all distros are affected by it ?

Sorry, I don’t have any names at the moment. I think it would be wise to wait and see if someone has an issue, and then go from there, instead of trying to find them.

**Pull request merged**
